### ISSUE TITLE
[Feature Request] Implement yt-dlp

### ISSUE THREAD

**Issue by venttarc** [abdallahmehiz/mpvKt#134] opened 2024-11-03 13:03 UTC
Hello there. This is a quite big thing to ask but it would be very helpful if you could implement [yt-dlp](https://github.com/yt-dlp/yt-dlp) inside mpvKt.

**Why?** in desktop or laptops, when MPV is installed in the system, we can integrate yt-dlp binary file inside mpv with the mpv.conf file and stream Youtube,facebook and videos from more platform directly. But in mpvKt, even if we modify the config file and command it to use yt-dlp bin, it won't work because mpvKt is a standalone app.

**What will we get?**
- Stream YouTube videos
- Stream videos from Facebook and other platforms that you can't access without cookies
- Less storage as we'll stream instead of downloading videos.

Looking forward to a feedback

**Comment by Anthonyy232** [comment] 2024-11-03 18:12
Personally this would be very useful for me too, however I believe it won't be allowed on the play store if it does, which means this may need to be a separate flavor if implemented

**Comment by uugaabuugaa** [comment] 2024-11-03 20:37
You can still implement network stream and block YouTube url requests. There are a lot of apps popular on play store that do network streams with or without YouTube.

**Comment by venttarc** [comment] 2024-11-03 23:16
> You can still implement network stream and block YouTube url requests. There are a lot of apps popular on play store that do network streams with or without YouTube.

You have a great point brother. But YouTube streaming is another reason why I opened this issue lmao

**Comment by uugaabuugaa** [comment] 2024-11-04 05:39
yeah I'm all for yt-dlp. i just suggested it since the devs aren't that willing to include it in play store. We can have a github only version for yt-dlp included version or something like the one in [yt-dlp included mpv-android](https://github.com/mpv-android/mpv-android/pull/58#issue-247852413) that updates it's download link everytime the app is updated.

**Comment by abdallahmehiz** [comment] 2024-11-04 06:06
I am planning to implement the same feature but it's not a priority right now.
Oh, Ig this issue is a duplicate of #3 so I am closing it for now, discussions should continue there.

**Closed by abdallahmehiz** 2024-11-04 06:06 UTC
