### ISSUE TITLE
Feature request : Add audio mode

### ISSUE THREAD

**Issue by zhengqwe** [abdallahmehiz/mpvKt#80] opened 2024-09-13 13:02 UTC
Add audio mode, like VLC, it can play pure audio content. VLC has problems playing some audio m3u8 links.

**Comment by abdallahmehiz** [comment] 2024-09-13 13:39
You mean a music player UI?

**Comment by aqtoo** [comment] 2024-09-13 21:33
I think they mean a way so it just plays the audio of a file so they can listen to it in the background, I would also like an audio button.

**Comment by abdallahmehiz** [comment] 2024-09-14 15:19
the it's a duplicate of #10

**Closed by abdallahmehiz** 2024-09-14 15:19 UTC
