### ISSUE TITLE
Continue playing when minimized without PiP mode

### ISSUE THREAD

**Issue by lamyergeier** [abdallahmehiz/mpvKt#81] opened 2024-09-13 23:28 UTC
VLC does that. Useful when I just want to listen the audio from the video.

**Comment by mxmilkiib** [comment] 2024-10-26 15:15
This would be so incredibly appreciated, I can't use the app to listen to music, audiobooks, or video audio (DJ mixes, video podcasts, etc.) as I would do without this

**Comment by abdallahmehiz** [comment] 2024-10-26 16:52
duplicate of #10

**Closed by abdallahmehiz** 2024-10-26 16:52 UTC
