### ISSUE TITLE
"Hold for x2 speed" toggle does not work properly

### ISSUE THREAD

**Issue by anhminhpho** [abdallahmehiz/mpvKt#79] opened 2024-09-13 01:45 UTC
**Describe the bug**
Toggling off "Hold for x2 speed" does not work.

**To Reproduce**
1. Toggle off "Hold for x2 speed" in the settings menu, in "Player"
2. Play a video file
3. Tap and hold on the screen

**Expected behavior**
"Hold for x2 speed" should be disabled.

**Actual behavior**
"Hold for x2 speed" still works.

**Additional info (please complete the following information):**
 - Device: Xperia 5 III
 - Android version: 13
 - App Version: 0.1.5

Great app, much needed improvements over stock mpv. Thank you!

**Comment by abdallahmehiz** [comment] 2024-09-13 08:57
Duplicate of #67 
Fixed on 9f75cd138811fda4f677ebc4d7cdb6ca47cc7ff7

**Closed by abdallahmehiz** 2024-09-13 08:57 UTC
