### ISSUE TITLE
Purple Screen Issue While Playing Videos in Mpvkt v0.1.6 (Audio Works but Video Fails) 

### ISSUE THREAD

**Issue by MOAZ-JR** [abdallahmehiz/mpvKt#179] opened 2024-12-18 20:17 UTC
Describe the bug
When playing a video in the Mpvkt app, the screen turns purple, as shown in the attached screenshot, while the audio continues to play in the background. The issue is only resolved by closing and reopening the app.

To Reproduce

1. Open the Mpvkt app.

2. Play a video file (e.g., Robin.Hood.2018.1080p.BluRay.x265).

3. While the video is playing, the screen turns purple.

4. The audio continues to play, but no video is displayed.

Expected behavior
The video should play normally with both audio and video functioning simultaneously.

Actual behavior
The screen turns purple, and only the audio continues playing in the background.

Crash logs
Not available.

Screenshots
![Screenshot_20241218_220638.jpg](https://github.com/user-attachments/assets/04bcf825-8827-49a7-8417-2833a5028d31)

Additional info (please complete the following information):

Device: Honor X9a

Android version: 13

App Version: 0.1.6

**Comment by abdallahmehiz** [comment] 2024-12-18 20:20
A known issue.
You can mitigate it by not using `gpu-next`
Disable it from the Decoder settings.
https://github.com/mpv-android/mpv-android/issues/977

Closed cause it's a duplicate of #84

**Closed by abdallahmehiz** 2024-12-18 20:20 UTC
