### ISSUE TITLE
[feature request] background playback 

### ISSUE THREAD

**Issue by Sensex00** [abdallahmehiz/mpvKt#73] opened 2024-09-12 08:38 UTC
Add option in more menu or through other options to play video in background 

![Screenshot_2024-09-12-14-06-26-875_live mehiz mpvkt preview](https://github.com/user-attachments/assets/10845782-a99e-4374-9a8d-3cac7b6d7340)

**Comment by abdallahmehiz** [comment] 2024-09-12 11:04
duplicate of #10

**Closed by abdallahmehiz** 2024-09-12 11:04 UTC
